# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://kurtrooks.com
baseurl: /
title: Kurt Rooks
author: Kurt Rooks
description: Kurt Rooks - maker,tinkerer,jack of all trades
avatar: profile.png
email: kurt@kurtrooks.com
twitter: kurt_rooks
instagram: kurt_rooks
youtube: bonafidegeek
#github: 
#linkedin: 
#stackoverflow:
#Comment out if you don't want disqus
#disqus: 
google_analytics: UA-176423965-1

# needed for travis-ci build
exclude: [vendor]

theme: jekyll-theme-minimal
